name: Dart

on: [push]
env:
  VERSION: flutter --version
jobs:
  flutter_test:
    name: flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
      - name: check out
        uses: actions/checkout@v2

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/app-release.aab"
          tag: 0.1
          token: ${{ secrets.test }}
          prerelease: false
          
      - name: upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
      - name: check out  
        uses: actions/checkout@v2
      - name: download
        uses: actions/download-artifact@v3.0.0
        with:
          name: release-apk
        
      - uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app-release.apk
